[project]
name = 'Waste-Management-and-Recycling-Incentive-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.recycling-rewards]
path = 'contracts/recycling-rewards.clar'
clarity_version = 2
epoch = 2.5

[contracts.waste-management]
path = 'contracts/waste-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
